### ISSUE TITLE
有个人封装了一下新的API，up可以看看

### ISSUE THREAD

**Issue by meidiei** [lgc-NB2Dev/nonebot-plugin-akinator#11]
https://github.com/advnpzn/akipy

**Comment by lgc2333** [comment]
related with #10

**Comment by lgc2333** [comment]
正在解决 https://github.com/lgc2333/cooaki

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-akinator/releases/tag/v1.0.1
