### ISSUE TITLE
希望增加将游戏通过私聊（临时聊天）进行的配置项

### ISSUE THREAD

**Issue by Jerry-Z07** [lgc-NB2Dev/nonebot-plugin-akinator#13]
一直在群里发送消息其实也~~挺烦的~~，特别是对于群管理  
设想是在群里发送``aki``开始游戏，然后机器人开启临时会话与使用者交互  
谢谢大佬了

**Comment by lgc2333** [comment]
不推荐使用临时会话，自己私聊使用
