### ISSUE TITLE
[BUG]获取到的session有误，导致回答完第一问后，直接判定没有更多问题，游戏结束

### ISSUE THREAD

**Issue by Elan114514** [lgc-NB2Dev/nonebot-plugin-akinator#15]
近期发现akinator回答完第一问后立即回复“想不出更多问题了”，直接结束游戏
使用cooaki库进行调试，发现回答完第一问后，akinator都会返回{"completion":"KO"}，直接判定玩家胜利，结束游戏。
这是具体的返回：
{'step': 0, 'progression': 0.0, 'sid': 1, 'cm': False, 'session': 'sen9g9+Yj2ha4t+vb2mKDQMV5RL9W7HrA6nBg3ASAOX+Oim27wZXoIkNYUNxoIaW/Pnr4TCtIYWQr63u5Qcnmw==', 'signature': 'sen9g9+Yj2ha4t+vb2mKDQMV5RL9W7HrA6nBg3ASAOX+Oim27wZXoIkNYUNxoIaW/Pnr4TCtIYWQr63u5Qcnmw==', 'answer': 0, 'step_last_proposition': ''}
{"completion":"KO"}
可以发现这里获取到的session是错误的，它应当是一个整数，或许就是session错误导致提交了无效的请求，进而导致akinator返回{"completion":"KO"}。

我尝试修改了cooaki库中session和signature的获取方法，获取到正确的session后，就能正常执行问答流程了

session_match = re.search(r'name="session"\s+id="session"\s+value="([^"]+)"', resp_text)
signature_match = re.search(r'name="signature"\s+id="signature"\s+value="([^"]+)"', resp_text)

**Comment by lgc2333** [comment]
#15

**Comment by lgc2333** [comment]
请问是否有兴趣给cooaki库PR
https://github.com/lgc2333/cooaki
