### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by MomentQYC** [lgc-NB2Dev/nonebot-plugin-akinator#4]
请问是需要安装什么字体吗，我设好后全是方块

**Comment by lgc2333** [comment]
https://github.com/MeetWq/pil-utils/#%E9%85%8D%E7%BD%AE%E5%AD%97%E4%BD%93

**Comment by MomentQYC** [comment]
> https://github.com/MeetWq/pil-utils/#%E9%85%8D%E7%BD%AE%E5%AD%97%E4%BD%93

已解决，感谢
