### ISSUE TITLE
报错“指定的网络名不再可用”

### ISSUE THREAD

**Issue by a930389426** [lgc-NB2Dev/nonebot-plugin-akinator#5]
![image](https://user-images.githubusercontent.com/59648220/232716862-98ded8dc-e301-46eb-853b-ae7dedb31ff4.png)

**Comment by a930389426** [comment]
![image](https://user-images.githubusercontent.com/59648220/232717836-1bedac14-d126-4e3c-9d0a-ab814a9e6a0a.png)

**Comment by lgc2333** [comment]
#2
