### ISSUE TITLE
文字无法正常显示

### ISSUE THREAD

**Issue by elit06** [lgc-NB2Dev/nonebot-plugin-akinator#6]
![QQ图片20230419215054](https://user-images.githubusercontent.com/82104958/233096538-cc6c8cf5-3187-4726-af14-ceaae8d96f37.jpg)
已安装中文字符集与中文字体
![屏幕截图 2023-04-19 215259](https://user-images.githubusercontent.com/82104958/233096863-107dfef7-4bcf-4f65-a372-02a4d8bb53cb.png)
![屏幕截图 2023-04-19 215457](https://user-images.githubusercontent.com/82104958/233097474-b58b8966-0a43-4475-aa26-5fe6f70d4d4e.png)
txt2img 运行正常，其他使用txt2img的插件文字显示正常

**Comment by lgc2333** [comment]
https://github.com/MeetWq/pil-utils#%E9%85%8D%E7%BD%AE%E5%AD%97%E4%BD%93

![image](https://user-images.githubusercontent.com/59048777/233101552-b88f1f8b-ba54-4dbd-b6a5-030eba62a922.png)

**Comment by elit06** [comment]
已解决，感谢
